export default [
  'Antibiotics',
  'Allergenics',
  'Alternative Medicines',
  'Anti-Infectives',
  'Antineoplastics',
  'Biologicals',
  'Cardiovascular Agents',
  'Central Nervous System Agents',
  'Coagulation Modifiers',
  'Gastrointestinal Agents',
  'Genitourinary Tract Agents',
  'Hormones',
  'Immunologic Agents',
  'Metabolic Agents',
  'Miscellaneous Agents',
  'Nutritional Products',
  'Plasma Expanders',
  'Psychotherapeutic Agents',
  'Radiologic Agents',
  'Respiratory Agents',
  'Topical Agents'
]
