export default [
  {
    type: 'Antibiotics',
    name: 'Amoxicillin',
    brand: 'Novamox',
    class: 'Penicillins',
    id: 'DB01060',
  },
  {
    type: 'Antibiotics',
    name: 'Amoxicillin/Clavulanate',
    brand: 'Augmentin',
    class: 'Penicillins',
    id: 'DB01061',
  },
  {
    type: 'Antibiotics',
    name: 'Ampicillin/Sulbactam',
    brand: 'Unasyn',
    class: 'Penicillins',
    id: 'DB01062',
  },
  {
    type: 'Antibiotics',
    name: 'Piperacillin/Tazobactam',
    brand: 'Zosyn',
    class: 'Penicillins',
    id: 'DB01063',
  },
  {
    type: 'Antibiotics',
    name: 'Ticarcillin/Clavulanate',
    brand: 'Timentin',
    class: 'Penicillins',
    id: 'DB01064',
  },
  {
    type: 'Antibiotics',
    name: 'Cefadroxil',
    brand: 'Duricef',
    class: 'Cephalosporins',
    id: 'DB01140',
  },
  {
    type: 'Antibiotics',
    name: 'Cefazolin',
    brand: 'Ancef',
    class: 'Cephalosporins',
    id: 'DB01327',
  },
  {
    type: 'Antibiotics',
    name: 'Cefalexin',
    brand: 'Keflex',
    class: 'Cephalosporins',
    id: 'DB00567',
  },
  {
    type: 'Antibiotics',
    name: 'Cefaclor',
    brand: 'Distaclor',
    class: 'Cephalosporins',
    id: 'DB00833',
  },
  {
    type: 'Antibiotics',
    name: 'Cefprozil',
    brand: 'Cefzil',
    class: 'Cephalosporins',
    id: 'DB01150',
  },
  {
    type: 'Antibiotics',
    name: 'Cefotaxime',
    brand: 'Ceftin',
    class: 'Cephalosporins',
    id: 'DB00493',
  },
  {
    type: 'Antibiotics',
    name: 'Cefixime',
    brand: 'Cefspan',
    class: 'Cephalosporins',
    id: 'DB00671',
  },
  {
    type: 'Antibiotics',
    name: 'Cefdinir',
    brand: 'Omnicef',
    class: 'Cephalosporins',
    id: 'DB00535',
  },
  {
    type: 'Antibiotics',
    name: 'Cefditoren',
    brand: 'Spectracef',
    class: 'Cephalosporins',
    id: 'DB01066',
  },
  {
    type: 'Antibiotics',
    name: 'Cefotaxime',
    brand: 'Claforan',
    class: 'Cephalosporins',
    id: 'DB00493',
  },
  {
    type: 'Antibiotics',
    name: 'Azithromycin',
    brand: 'Zithromax',
    class: 'Macrolides',
    id: 'DB00207',
  },
  {
    type: 'Antibiotics',
    name: 'Clarithromycin',
    brand: 'Biaxin',
    class: 'Macrolides',
    id: 'DB01211',
  },
  {
    type: 'Antibiotics',
    name: 'Erythromycin',
    brand: 'Erythocin',
    class: 'Macrolides',
    id: 'DB00199',
  },
  {
    type: 'Antibiotics',
    name: 'Telithromycin',
    brand: 'Ketek',
    class: 'Macrolides',
    id: 'DB00976',
  },
  {
    type: 'Antibiotics',
    name: 'Spiramycin',
    brand: 'Rovamycine',
    class: 'Macrolides',
    id: 'DB06145',
  },
  {
    type: 'Antibiotics',
    name: 'Ciprofloxacin',
    brand: 'Ciproxin',
    class: 'Fluoroquinolones',
    id: 'DB00537',
  },
  {
    type: 'Antibiotics',
    name: 'Enoxacin',
    brand: 'Penetrex',
    class: 'Fluoroquinolones',
    id: 'DB00467',
  },
  {
    type: 'Antibiotics',
    name: 'Gatifloxacin',
    brand: 'Tequin',
    class: 'Fluoroquinolones',
    id: 'DB01044',
  },
  {
    type: 'Antibiotics',
    name: 'Gemifloxacin',
    brand: 'Factive',
    class: 'Fluoroquinolones',
    id: 'DB01155',
  },
  {
    type: 'Antibiotics',
    name: 'Levofloxacin',
    brand: 'Levaquin',
    class: 'Fluoroquinolones',
    id: 'DB01137',
  },
  {
    type: 'Antibiotics',
    name: 'Lomefloxacin',
    brand: 'Maxaquin',
    class: 'Fluoroquinolones',
    id: 'DB00978',
  },
  {
    type: 'Antibiotics',
    name: 'Moxifloxacin',
    brand: 'Avelox',
    class: 'Fluoroquinolones',
    id: 'DB00218',
  },
  {
    type: 'Antibiotics',
    name: 'Nalidixic acid',
    brand: 'NegGram',
    class: 'Fluoroquinolones',
    id: 'DB00779',
  },
  {
    type: 'Antibiotics',
    name: 'Norfloxacin',
    brand: 'Noroxin',
    class: 'Fluoroquinolones',
    id: 'DB01059',
  },
  {
    type: 'Antibiotics',
    name: 'Demeclocycline',
    brand: 'Declomycin',
    class: 'Tetracyclines',
    id: 'DB00618',
  },
  {
    type: 'Antibiotics',
    name: 'Minocycline',
    brand: 'Minocin',
    class: 'Tetracyclines',
    id: 'DB01017',
  },
  {
    type: 'Antibiotics',
    name: 'Oxytetracycline',
    brand: 'Terramycin',
    class: 'Tetracyclines',
    id: 'DB00595',
  },
  {
    type: 'Antibiotics',
    name: 'Tetracycline',
    brand: 'Sumycin',
    class: 'Tetracyclines',
    id: 'DB00759',
  },
  {
    type: 'Antibiotics',
    name: 'Amikacin',
    brand: 'Amikin',
    class: 'Aminoglycosides',
    id: 'DB00479',
  },
  {
    type: 'Antibiotics',
    name: 'Gentamicin',
    brand: 'Garamycin',
    class: 'Aminoglycosides',
    id: 'DB00798',
  },
  {
    type: 'Antibiotics',
    name: 'Kanamycin',
    brand: 'Kantrex',
    class: 'Aminoglycosides',
    id: 'DB01172',
  },
  {
    type: 'Antibiotics',
    name: 'Neomycin',
    brand: 'Neo-Fradin',
    class: 'Aminoglycosides',
    id: 'DB00994',
  },
  {
    type: 'Antibiotics',
    name: 'Netilmicin',
    brand: 'Netromycin',
    class: 'Aminoglycosides',
    id: 'DB00955',
  },
  {
    type: 'Antibiotics',
    name: 'Tobramycin',
    brand: 'Nebcin',
    class: 'Aminoglycosides',
    id: 'DB00684',
  },
  {
    type: 'Antibiotics',
    name: 'Paromomycin',
    brand: 'Humatin',
    class: 'Aminoglycosides',
    id: 'DB01421',
  },
  {
    type: 'Antibiotics',
    name: 'Spectinomycin',
    brand: 'Trobicin',
    class: 'Aminoglycosides',
    id: 'DB00919',
  },
  {
    type: 'Antibiotics',
    name: 'Mafenide',
    brand: 'Sulfamylon',
    class: 'Sulfonamides',
    id: 'DB06795',
  },
  {
    type: 'Antibiotics',
    name: 'Sulfacetamide',
    brand: 'Sulamyd',
    class: 'Sulfonamides',
    id: 'DB00634',
  },
  {
    type: 'Antibiotics',
    name: 'Sulfadiazine',
    brand: 'Micro-Sulfon',
    class: 'Sulfonamides',
    id: 'DB00359',
  },
  {
    type: 'Antibiotics',
    name: 'Silver sulfadiazine',
    brand: 'Silvadene',
    class: 'Sulfonamides',
    id: 'DB05245',
  },
  {
    type: 'Antibiotics',
    name: 'Sulfadimethoxine',
    brand: 'Di-Methox',
    class: 'Sulfonamides',
    id: 'DB06150',
  },
  {
    type: 'Antibiotics',
    name: 'Sulfamethizole',
    brand: 'Thiosulfil Forte',
    class: 'Sulfonamides',
    id: 'DB00576',
  },
  {
    type: 'Antibiotics',
    name: 'Sulfamethoxazole',
    brand: 'Gantanol',
    class: 'Sulfonamides',
    id: 'DB01015',
  },
  {
    type: 'Antibiotics',
    name: 'Sulfasalazine',
    brand: 'Sulfasalazine',
    class: 'Sulfonamides',
    id: 'DB00795',
  },
  {
    type: 'Antibiotics',
    name: 'Sulfisoxazole',
    brand: 'Gantrisin',
    class: 'Sulfonamides',
    id: 'DB00263',
  },
  {
    type: 'Antibiotics',
    name: 'Carbamazepine',
    brand: 'Tegretol',
    class: 'Anticonvulsants',
    id: 'DB00564',
  },
  {
    type: 'Antibiotics',
    name: 'Phenytoin',
    brand: 'Dilantin',
    class: 'Anticonvulsants',
    id: 'DB00252',
  },
  {
    type: 'Antibiotics',
    name: 'Phenobarbital',
    brand: 'Luminal',
    class: 'Anticonvulsants',
    id: 'DB01174',
  },
  {
    type: 'Antibiotics',
    name: 'Lamotrigine',
    brand: 'Lamictal',
    class: 'Anticonvulsants',
    id: 'DB00555',
  },
  {
    type: 'Antibiotics',
    name: 'Fosphenytoin',
    brand: 'Cerebyx',
    class: 'Anticonvulsants',
    id: 'DB01320',
  },
  {
    type: 'Antibiotics',
    name: 'Valproic acid',
    brand: 'Depakene',
    class: 'Anticonvulsants',
    id: 'DB00313',
  },
  {
    type: 'Respiratory Agents',
    name: 'Dyphylline/Guaifenesin',
    brand: 'Difil-G Forte',
    class: 'Antiasthmatic Combinations',
    id: 'DB00651/DB00874',
  },
  {
    type: 'Respiratory Agents',
    name: 'Dyphylline/Guaifenesin',
    brand: 'Dilex-G 400',
    class: 'Antiasthmatic Combinations',
    id: 'DB00651/DB00874',
  },
  {
    type: 'Respiratory Agents',
    name: 'Dyphylline/Guaifenesin',
    brand: 'Dy-G',
    class: 'Antiasthmatic Combinations',
    id: 'DB00651/DB00874',
  },
  {
    type: 'Respiratory Agents',
    name: 'Dyphylline/Guaifenesin',
    brand: 'Jay-Phyl',
    class: 'Antiasthmatic Combinations',
    id: 'DB00651/DB00874',
  },
  {
    type: 'Respiratory Agents',
    name: 'Dyphylline/Guaifenesin',
    brand: 'Lufyllin-GG',
    class: 'Antiasthmatic Combinations',
    id: 'DB00651/DB00874',
  },
  {
    type: 'Respiratory Agents',
    name: 'Fexofenadine',
    brand: 'Allegra ODT',
    class: 'Antihistamines',
    id: 'DB00950',
  },
  {
    type: 'Respiratory Agents',
    name: 'Terfenadine',
    brand: 'Seldane',
    class: 'Antihistamines',
    id: 'DB00342',
  },
  {
    type: 'Respiratory Agents',
    name: 'Triprolidine',
    brand: 'Zymine',
    class: 'Antihistamines',
    id: 'DB00427',
  },
  {
    type: 'Respiratory Agents',
    name: 'Chlorpheniramine',
    brand: 'Chlor-Trimeton',
    class: 'Antihistamines',
    id: 'DBSALT000987',
  },
  {
    type: 'Respiratory Agents',
    name: 'Cetirizine',
    brand: 'All Day Allergy',
    class: 'Antihistamines',
    id: 'DB00341',
  },
  {
    type: 'Respiratory Agents',
    name: 'Diphenhydramine',
    brand: 'Compoz Nighttime Sleep Aid',
    class: 'Antihistamines',
    id: 'DB01075',
  },
]